name: Two Wheels One journey
favicon: null
layout_spectrum: 0.85066
typography_spectrum: 0.65287
title: Two Wheels One journey
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171516'
    - '#6195c4'
    - '#44698e'
    - '#c3b39b'
    - '#e3eaf2'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
