name: Two Wheels One journey
favicon: null
layout_spectrum: 0.7459927881136537
typography_spectrum: 0.18469324032776058
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.20890509895980358
  lightness: 0.38839738559909165
  saturation: 0.8592899770010263
  rhythmicContrast: 0.9874000805430114
purpose: []
