name: Two Wheels One journey
favicon: null
layout_spectrum: 0.73679
typography_spectrum: 0.43394
title: Two Wheels One journey
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#16130e'
    - '#6e6d69'
    - '#b09b84'
    - '#90190b'
  brandStrength: 0.4375
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
